#pragma once

/**
 * @file dart_mesh2.hpp
 * @brief Mesh with topology defined by a combinatorial map
 */
#include "mathutils/mesh/mesh_common.hpp"
#include "mathutils/simple_generator.hpp"
#include <unordered_set>
// #include "mathutils/mesh/mesh_plyio.hpp"
// #include "mathutils/simple_generator.hpp"

namespace mathutils {
namespace mesh {
/** @addtogroup Mesh
 *  @{
 */

class DartTopology2 {
  using Generatori = mathutils::SimpleGenerator<Index>;

public:
  SamplesIndex d_through_S0_;
  SamplesIndex d_through_S1_;
  SamplesIndex d_through_S2_;

  SamplesIndex s0_in_D_;
  SamplesIndex s1_in_D_;
  SamplesIndex s2_in_D_;

  SamplesIndex d_cmap0_D_;
  SamplesIndex d_cmap1_D_;
  SamplesIndex d_cmap2_D_;

private:
  // Generatori generate_D_orbit_d(Index d0, const SamplesIndex &d_cmapA_D,
  //                               const SamplesIndex &d_cmapB_D,
  //                               const size_t dart_bound = 16) const {
  //   std::vector<Index> stack;
  //   stack.reserve(dart_bound);
  //   stack.push_back(d0);
  //
  //   std::unordered_set<Index> seen;
  //   seen.reserve(dart_bound);
  //   seen.insert(d0);
  //
  //   co_yield d0;
  //
  //   std::array<const SamplesIndex *, 2> cmaps{&d_cmapA_D, &d_cmapB_D};
  //   while (!stack.empty()) {
  //     Index d = stack.back();
  //     stack.pop_back();
  //
  //     for (const auto *cmap : cmaps) {
  //       Index dn = (*cmap)[d];
  //       if (seen.insert(dn).second) {
  //         stack.push_back(dn);
  //         co_yield dn;
  //       }
  //     }
  //   }
  //
  //   co_return;
  // }

  // /**
  //  * @brief Dart orbit generated by vector of combinatorial maps
  //  */
  // Generatori
  // generate_D_orbit_d(Index d0,
  //                    std::vector<const SamplesIndex *>
  //                        cmaps, // arbitrary number of cmaps, but slower
  //                    const size_t dart_bound = 16) const {
  //   std::vector<Index> stack;
  //   stack.reserve(dart_bound);
  //   stack.push_back(d0);
  //
  //   std::unordered_set<Index> seen;
  //   seen.reserve(dart_bound);
  //   seen.insert(d0);
  //
  //   co_yield d0;
  //
  //   while (!stack.empty()) {
  //     Index d = stack.back();
  //     stack.pop_back();
  //
  //     for (const auto *cmap : cmaps) {
  //       Index dn = (*cmap)[d];
  //       if (seen.insert(dn).second) {
  //         stack.push_back(dn);
  //         co_yield dn;
  //       }
  //     }
  //   }
  //
  //   co_return;
  // }
  /**
   * @brief Dart orbit generated by vector of combinatorial maps
   */
  Generatori generate_D_orbit_d(Index d0,
                                std::array<const SamplesIndex *, 2> cmaps,
                                const size_t dart_bound = 16) const {
    std::vector<Index> stack;
    stack.reserve(dart_bound);
    stack.push_back(d0);

    std::unordered_set<Index> seen;
    seen.reserve(dart_bound);
    seen.insert(d0);

    co_yield d0;

    while (!stack.empty()) {
      Index d = stack.back();
      stack.pop_back();

      for (const auto *cmap : cmaps) {
        Index dn = (*cmap)[d];
        if (seen.insert(dn).second) {
          stack.push_back(dn);
          co_yield dn;
        }
      }
    }

    co_return;
  }

public:
  // Generatori generate_D_through_s0(Index s) const {
  //   return generate_D_orbit_d(d_through_S0_[s], d_cmap1_D_, d_cmap2_D_, 20);
  // }

  Generatori generate_D_through_s0(Index s) const {
    return generate_D_orbit_d(d_through_S0_[s], {&d_cmap1_D_, &d_cmap2_D_}, 20);
  }

  Generatori generate_D_through_s1(Index s) const {
    return generate_D_orbit_d(d_through_S1_[s], {&d_cmap0_D_, &d_cmap2_D_}, 4);
  }

  Generatori generate_D_through_s2(Index s) const {
    return generate_D_orbit_d(d_through_S2_[s], {&d_cmap0_D_, &d_cmap1_D_}, 6);
  }
};

/**
@} // addtogroup Mesh
*/
} // namespace mesh
} // namespace mathutils
